### ISSUE TITLE
Error while compiling /usr/share/common-lisp/source/slime/swank-sbcl.lisp

### ISSUE THREAD

**Issue by jo5ch** [slime/slime#223] opened 2015-01-24 09:15 UTC
Although I have compiled and installed the recent versions of sbcl and slime (both from git at the current master branch, I've adapted my init.el accordingly), I still get the following compilation error when executing M-x slime in emacs, which seemingly was already spotted in earlier releases.

 caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "CODE-TRACE-TABLE-OFFSET-SLOT" not found in the SB-VM package.
;   
;       Line: 1478, Column: 70, File-Position: 58960
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /usr/share/common-lisp/source/slime/swank-sbcl.lisp"
;                 {1005326AE3}>
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 ERROR condition
;   printed 1 note
; compilation aborted after 0:00:00.583
;; 
;; Error while compiling /usr/share/common-lisp/source/slime/swank-sbcl.lisp:
;;   COMPILE-FILE returned NIL.
;; Aborting.

**Comment by luismbo** [comment] 2015-01-24 11:37
This smells like a duplicate of issue #222, so the same workaround should work **but** this shouldn't happen. Can you help me debug this?

First off, I'll ask the same question I did on the other issue. What's the value of `slime-path` on the Emacs side? And what's the value of `swank-loader:*source-directory*` on the Lisp side after you start it with `M-x slime`? You're getting an error during loading but you can probably still evaluate that variable in the `*inferior-lisp*` buffer, I hope.

Second, SWANK is being loaded from `/usr/share/common-lisp/source/slime/`. I'm guessing that's not where you checked out the git version of SLIME. That is probably an old version that you installed via your distribution's package system. So, uninstalling that is likely to fix your problem. But, again, that shouldn't be a problem and I'd like to figure out why SLIME is picking that up.

Hmm, what does value does `slime-backend` have on the Emacs side?

**Comment by jo5ch** [comment] 2015-01-24 12:23
Thank you for your effort!

slime-path: "/usr/share/emacs/site-lisp/site-start.d/"
swank-loader:*source-directory* after running M-x slime:  "/usr/share/common-lisp/source/slime/"
slime-backend: "/usr/share/common-lisp/source/slime/swank-loader.lisp"

I guess you are right with the old sbcl installation, but the version is also pretty decent (1.2.4).

**Comment by luismbo** [comment] 2015-01-24 12:41
No, I meant. Your version of SLIME (not SBCL) is old. So, your problem is different from #222. You're simply loading an old version of SLIME that you've installed using your Linux distribution. Uninstall that and your problem should go away.

**Closed by luismbo** 2015-01-24 12:41 UTC

**Comment by jo5ch** [comment] 2015-01-24 13:29
Thank you, that was something I've completely overlooked. I apologize for my stupidity.^^

**Comment by luismbo** [comment] 2015-01-24 13:57
No problem. :-)
