### ISSUE TITLE
Debian Jessie, SBCL, Couldn't load "/usr/share/common-lisp/source/slime/swank-loader.lisp": file   does not exist.

### ISSUE THREAD

**Issue by martinvlk** [slime/slime#238] opened 2015-03-23 19:31 UTC
Hi, I have just installed slime in emacs 24.4.1 from MEPL.
```
slime is an installed package.

     Status: Installed in `~/.emacs.d/elpa/slime-20150304.1145/' (unsigned).
    Archive: n/a
    Version: 20150304.1145
   Requires: cl-lib-0.5
    Summary: Superior Lisp Interaction Mode for Emacs
   Homepage: https://github.com/slime/slime
   Keywords: languages lisp slime 
    Other versions: 20150304.1145 (melpa).
```
I set the following in my init.el 
`(setq inferior-lisp-program "/usr/bin/sbcl")`

Now when I do M-x slime, I get the following.
```
debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10039CED73}>:
  Couldn't load "/usr/share/common-lisp/source/slime/swank-loader.lisp": file
  does not exist.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(LOAD "/usr/share/common-lisp/source/slime/swank-loader.lisp" :VERBOSE T :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
```

I couldn't find any mentions of this issue on the web, so reporting as a problem here.

**Comment by luismbo** [comment] 2015-03-23 22:47
It seems you have also installed slime via Debian's package system. Can you make sure you've removed all traces of such an installation?

**Comment by martinvlk** [comment] 2015-03-24 08:09
Hi, I did remove and purge the Debian package which in theory means it should be gone completely.
Could you suggest where to look for reminding traces that could cause this issue? Maybe the Debain package doesn't properly purge the package and it needs to be fixed...

Many Thanks
Martin

**Comment by luismbo** [comment] 2015-03-24 08:18
Have a look at the slime-path variable on the Emacs side. It probably points to where the Debian-provided version is. Or perhaps `M-x describe-function slime` and see where that function is defined (I suspect it, too, will be in some Debian-specific location.) 

Hope that helps! Let me know.

**Comment by martinvlk** [comment] 2015-03-24 08:36
I have tried that and the slime function comes from the slime dir I installed from melpa.
I looked for slime-path and this is what I see in slime.el ->
```
(defvar slime-path nil
  "Directory containing the Slime package.
This is used to load the supporting Common Lisp library, Swank.
The default value is automatically computed from the location of
the Emacs Lisp package.")
(setq slime-path (file-name-directory load-file-name))
```

So to me it looks like it assumes slime will be installed in the same location as emacs, which is not the case if I have a system installation of emacs and install any packages in user directory.

Is this a bug in slime then?

**Comment by martinvlk** [comment] 2015-03-24 12:35
I have been able to work around the problem by these steps.
* attempt starting slime (fails with the reported issue)
* abort connection attempt (slime-abort-connection)
* undo customization of the `slime-backend` option in Emacs - this removes the bad value and causes the code to go through different path where it resolves the backend file correctly
* save the Emacs options
* now I can run slime and it works

Interesting points:
* slime-backend option is not defined until I attempt to start slime
* the updated value is not saved - I have to repeat these steps every time I start Emacs

I think this means slime code is somehow not handling the slime-backend option correctly and it gets set to wrong value every time I start Emacs.

**Comment by luismbo** [comment] 2015-03-24 13:58
Cool. So the question is, who is messing with the slime-backend variable?

**Comment by martinvlk** [comment] 2015-03-24 14:09
One more thing, when I set `slime-backend` in my init.el to value `"swank-loader.lisp"` then it works as expected even after restarting Emacs. So the problem only happens when I don't set the value at all, in which case (I assume) the slime code takes over and calculates the wrong file location.

**Comment by luismbo** [comment] 2015-03-24 14:48
Right, but I'm pretty sure it's some Debian code that's messing with slime-backend.

**Comment by martinvlk** [comment] 2015-03-24 16:44
Ok, I found it - the culprit is indeed a config file (`/etc/emacs/site-start.d/50slime.el`) left behind by the removed Debian slime package. Closing this issue and will report it to Debian.

Sincere thanks for your help!

**Closed** 2015-03-24 16:44 UTC

**Comment by luismbo** [comment] 2015-03-24 17:57
Cool, how did you figure it out?

**Comment by martinvlk** [comment] 2015-03-24 18:56
By first looking at stack trace and slime.el I figured it was the `slime-backend` variable that had a wrong value. Then based on your comments I searched all of `/etc` for references to `slime-backend` - and that yielded that config file.

Simple - with the righ help from the right people. :-)
Thank once again.

**Comment by luismbo** [comment] 2015-03-24 19:16
Nicely done. I hope this helps other folks with the same issue in the future.

**Comment by martinvlk** [comment] 2015-03-24 19:25
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781118

**Comment by attila-lendvai** [comment] 2015-03-25 07:01
FTR, the last few comments of this thread is very educational regarding how to be helpful and how to always keep an eye on learning stuff that helps to be effective (directed curiosity).

dear participants, thanks for showing a good example!

dear readers, learn from this if you need to.

**Comment by mahouts** [comment] 2018-05-13 14:33
HI, I know that this issue had been closed for a long time, but I've just experienced the exact same bug. This thread saved me from some extreme frustration! Just thought I should let everyone know that this bug is still happening.

**Comment by stassats** [comment] 2018-05-13 17:06
It's not a bug, not a slime bug at least, but a misconfiguration issue.
