### ISSUE TITLE
OPERATION instances must only be created through MAKE-OPERATION.

### ISSUE THREAD

**Issue by pashosh** [slime/slime#373] opened 2017-03-19 08:05 UTC
i have sbcl 1.3.15 and latest quicklisp.
asdf version 3.2.0.
i can't install slime helper.
it happened both in archlinux and gentoo.

this is the full error:

* (ql:quickload "quicklisp-slime-helper")
To load "quicklisp-slime-helper":
  Load 1 ASDF system:
    swank
  Install 2 Quicklisp releases:
    alexandria quicklisp-slime-helper
; Fetching #<URL "http://beta.quicklisp.org/archive/alexandria/2017-02-27/alexandria-20170227-git.tgz">
; 49.95KB
==================================================
51,144 bytes in 0.17 seconds (295.53KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/quicklisp-slime-helper/2015-07-09/quicklisp-slime-helper-20150709-git.tgz">
; 2.16KB
==================================================
2,211 bytes in 0.00 seconds (0.00KB/sec)
; Loading "quicklisp-slime-helper"

debugger invoked on a ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR in thread
#<THREAD "main thread" RUNNING {100215E573}>:
  OPERATION instances must only be created through MAKE-OPERATION.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<NO-LOAD-FILE "swank" "contrib" "swank-c-p-c">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<NO-LOAD-FILE "swank" "contrib" "swank-c-p-c">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "quicklisp-slime-helper"
  5:                                 Exit debugger, returning to top level.

(ASDF/FIND-SYSTEM:SYSDEF-ERROR "OPERATION instances must only be created through MAKE-OPERATION.")
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL

**Comment by azimut** [comment] 2017-09-20 04:47
any known orkaround?

**Comment by luismbo** [comment] 2017-10-07 00:40
Can't reproduce with SBCL 1.4.0 and ASDF 3.3.0 or 3.1.5, sorry. I wonder if `(ql:update-client)` would help?

**Comment by luismbo** [comment] 2017-10-07 00:41
Closing until we have a recipe for reproducing the error.

**Closed by luismbo** 2017-10-07 00:41 UTC

**Comment by sharad** [comment] 2018-09-25 06:11
In my case with osicat package

If quicklisp client is old it may not update if client-info.sexp not exist

For this I had download some older client 
(ql-http:fetch "http://beta.quicklisp.org/client/2014-01-30/client-info.sexp" (ql-setup:qmerge "client-info.sexp"))
than come out of sbcl 
in next invokation 

did (ql:update-client) which updated the client to latest


Than agian I were seeing same error

for this now deleted all quicklisp cache

than (ql:quickload :osicat) properly installed and loaded.
