### ISSUE TITLE
NIL communication style doesn't work on CCL

### ISSUE THREAD

**Issue by VyacheslavMik** [slime/slime#440] opened 2018-03-28 10:41 UTC
This [documentation](https://common-lisp.net/project/slime/doc/html/Communication-style.html) say that I can use one of several communication styles. But none of ```nil```, ```:sigio``` or ```:fd-handler``` work with single threaded clozure-cl. I need slime with only one thread. You can see last 6 or 7 messages in this [issue](https://github.com/lispbuilder/lispbuilder/issues/54#issuecomment-376592306) in order to get the context. Thanks in advance.

**Comment by stassats** [comment] 2018-03-28 11:34
NIL communication style is such a poor experience that you'd better find a way to run your GUI on the main thread in some other way.

**Comment by VyacheslavMik** [comment] 2018-03-28 13:02
Ok. Thanks.

**Comment by stassats** [comment] 2018-03-28 14:25
Duplicate of #37

**Closed by stassats** 2018-03-28 14:25 UTC
