### ISSUE TITLE
Slime freezes when pressing tab in a string read by  (READ).

### ISSUE THREAD

**Issue by renzo-orsini** [slime/slime#330] opened 2016-08-07 06:55 UTC
Context: Emacs 24.5 on Mac OS X 10.11.6, Slime 2016-04-19

Action that causes the error:

in the REPL, write
    (READ)
and press return, then write 
  ab
and press TAB key.

Effect:

The system freezes. I can not give any command.

**Comment by luismbo** [comment] 2016-08-07 11:26
Duplicate of https://github.com/slime/slime/issues/329 which has been fixed. Should be in the next release. Cheers.

**Closed by luismbo** 2016-08-07 11:26 UTC
