### ISSUE TITLE
ABCL: frame-source-location fails

### ISSUE THREAD

**Issue by Enerccio** [slime/slime#752] opened 2023-02-04 15:20 UTC
It fails with condition ```There is no applicable method for the generic function #<STANDARD-GENERIC-FUNCTION SWANK/ABCL::SOURCE-LOCATION {5EB43D20}> when called with arguments ((:ANONYMOUS-INTERPRETED-FUNCTION)).```

**Comment by easye** [comment] 2023-02-05 13:52
@Enerccio again, a small reproducible test case would be helpful.

**Comment by Enerccio** [comment] 2023-02-05 15:28
Sorry, I am not using slime conventionally :) But now that you fixed the previous issue, the issue should be an easy to trigger. Simply call something with an error and then examine stack frames. The bottomless stackframe is anonymous interpreted function. If you then try to find source for that object it will fail with this. I know, it does not have a source but I don't think it should crash, instead it should return NIL or something similar for no source.

**Comment by easye** [comment] 2023-02-05 16:09
It doesn't matter if you aren't using SLIME "conventionally", it would still be helpful to have a simple way to reproduce the problem.  Surely you can isolate a piece of code which causes this problem?  I can't seem to reproduce it.

**Comment by Enerccio** [comment] 2023-02-05 17:12
I've overriden `backtrace` function in order to get all stack frame information in the backtrace:

```

(defslimefun backtrace (start end)
  (loop for frame in (compute-backtrace start end)
        for i from start collect
        (list i (frame-to-string frame)
                (format NIL "~A" (print-frame-call-place frame))
                (handler-case
                    (frame-source-location i)
                  (error (c) (format t "Error: ~A~%" c)
                             NIL))
                NIL)))


(defun print-frame-call-place (frame)
    (handler-case
        (if (typep frame 'sys::lisp-stack-frame)
            (first (sys::frame-to-list frame))
            (sys::frame-to-string frame))
      (error (c)
        (format t "Error: ~A~%" c))))
```

Ignore the `print-frame-call-place`, that is my function that prints the call name instead of default verbose call name + all the call variables. 

If you have this modification then after you evaluate a function, such as

```
(defun mobz () (error "Wut"))
```

and call it with repl

Resulting stacktrace will have this:

```
(:debug 7 1 ("Wut" "   [Condition of type SIMPLE-ERROR]" nil) (("RETRY" "Retry SLIME interactive evaluation request." :not-available) ("*ABORT" "Return to SLIME's top level." :not-available) ("ABORT" "Abort thread." :not-available)) ((0 "(INVOKE-DEBUGGER #<SIMPLE-ERROR {1697B05}>)" "INVOKE-DEBUGGER" nil nil) (1 "(ERROR \"Wut\")" "ERROR" nil nil) (2 "(MOBZ)" "MOBZ" (:location (:file "D:/test/untitled/src/foo.cl") (:function-name "MOBZ" :position 1) (:align t)) nil) (3 "(SYSTEM::%EVAL (MOBZ))" "%EVAL" (:location (:file "jar:file:///D:/tmp/abcl-bin-1.9.0/abcl.jar!/org/armedbear/lisp/Primitives.class") (:line 0) nil) nil) (4 "(EVAL (MOBZ))" "EVAL" (:location (:file "jar:file:///D:/tmp/abcl-bin-1.9.0/abcl.jar!/org/armedbear/lisp/boot.lisp") (:function-name "EVAL") (:align t)) nil) (5 "(#<ANONYMOUS-INTERPRETED-FUNCTION {11AC997}>)" "#<ANONYMOUS-INTERPRETED-FUNCTION {11AC997}>" nil nil)) (9))
```

And you get an error in stdout:

`Error: There is no applicable method for the generic function #<STANDARD-GENERIC-FUNCTION SWANK/ABCL::SOURCE-LOCATION {EC2541}> when called with arguments ((:ANONYMOUS-INTERPRETED-FUNCTION)).`

Hope this helps! 

The issue is that swank/abcl does not support frame evaluation so you can't do it manually.

**Comment by easye** [comment] 2023-08-18 15:48
I've implemented your backtrace mechanism, falling back to the original implementation in <https://github.com/easye/slime/commit/53dca453a4dd8122d4183e27da2f498a3722dd91>

Seems to work with abcl-1.9.2.  Closing for now, but please reopen if it is still a problem for you after updating.

**Comment by easye** [comment] 2023-08-27 18:18
Starting an instance of the Bear, naked of SLIME, then loading SLIME, defining at simple function which signals an error in the SWANK package, and invoking that function works as expected: 
```
[…]
SWANK(7): (defun mobz () (error "asdf"))

MOBZ
SWANK(8): (mobz)

#<THREAD "interpreter" native {5A12B9D}>: Debugger invoked on condition of type SIMPLE-ERROR
  asdf
Restarts:
  0: TOP-LEVEL Return to top level.
[1] SWANK(9): 0
```

Therefore seems to be a problem with your implementation of backtrace.    `swank/abcl.lisp` doesn't currently implement the `defslimefun` version of backtrace, but seems to work.  Perhaps we should try augmenting the current algorithm rather than using `defslimefun` first?

**Comment by easye** [comment] 2023-08-27 18:42
Ah, here's the problem:  the current implementation of `compute-backtrace` invokes `backtrace`, which is what is blowing up the stack on this code.  

See <https://github.com/slime/slime/blob/1e4b7417a1ade842ba4938f66445af68a93176b9/swank/abcl.lisp#L479>

@enerccio I would suggest rewriting your backtrace to fit in with how things are currently implemented in `swank/abcl.lisp`.  Because we have to work with the SLIME debugger invocation strategy, we actually do some complicated things that I don't fully understand completely.

**Closed by easye** 2023-08-27 18:42 UTC
